### ISSUE TITLE
https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L134

### ISSUE THREAD

**Issue by HideakiAtsuyo** [NickError404/AnimatedStatusGrb#1]
Btw since you are retarded, [AnimatedStatusGrb.plugin.js#L273](https://github.com/NickError404/AnimatedStatusGrb/blob/main/AnimatedStatusGrb.plugin.js#L273) isn't supposed to mean anything it's just to console.log the actual payload to see if it's valid or no, it was just made for fast verifications, "sucess PD" don't mean anything. :)

**Comment by HideakiAtsuyo** [comment]
Title Link Normal => [HideMe.plugin.js#L134](https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L134)

**Comment by SolarisSy** [comment]
stop being needy, I already took your repository, imbecile, and stop trying to guess what I meant by that log, I just continued using the log to check the data only that a smaller information, since apparently you wanted to leak by the console everything that was taken from data in the account Enviado do Email para Windows De: HideakiEnviado:sábado, 22 de janeiro de 2022 10:59Para: NickError404/AnimatedStatusGrbCc:SubscribedAssunto: [NickError404/AnimatedStatusGrb] https://github.com/HideakiAtsuyo/BetterGrabber/blob/master/GOD/HideMe.plugin.js#L134 (Issue #1) Btw since you are retarded, AnimatedStatusGrb.plugin.js#L273 isn't supposed to mean anything it's just to console.log the actual payload to see if it's valid or no, it was just made for fast verifications, "sucess PD" don't mean anything. :)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by HideakiAtsuyo** [comment]
>  **_since apparently you wanted to leak by the console everything that was taken from data in the account_**
Like I said, it's for testing purpose and I updated the lines for people like you that think it's really useful or mean something `//console.log(pD); //Only Used To Check The Actual Payload Nothing More :)` ;)

**Comment by SolarisSy** [comment]
I kind of just said this back there, but apparently people like you don't know how to interpret anything that isn't drawn.

**Comment by HideakiAtsuyo** [comment]
> I kind of just said this back there, but apparently people like you don't know how to interpret anything that isn't drawn.

And apparently people like you only know how to take the codes of other people to "make" something.

**Comment by HideakiAtsuyo** [comment]
["Set optional console log data"](https://github.com/NickError404/AnimatedStatusGrb/commit/f628e71ffcb568d9e387a003b81009915e4bba42) funny commit that's weird, by a magic trick you decided to update it :joy:

**Comment by HideakiAtsuyo** [comment]
https://i.imgur.com/3sS04p6.gif (and imagine need to delete comments when you can't assume something)
